# Generated by scripts/runtime_config.py from config/runtime-libraries.toml.
# Do not edit this file directly.
from __future__ import annotations

WINDOWS_LIBRARY_DIRECTORY = 'bin'

LINUX_LIBRARY_DIRECTORY = 'lib'

MACOS_LIBRARY_DIRECTORY = 'lib'

WINDOWS_LIBRARIES = (
    'libglib-2.0-0.dll',
    'libgobject-2.0-0.dll',
    'libgio-2.0-0.dll',
    'libfontconfig-1.dll',
    'libfreetype-6.dll',
    'libharfbuzz-0.dll',
    'libcairo-2.dll',
    'libpango-1.0-0.dll',
    'libpangoft2-1.0-0.dll',
    'libpangocairo-1.0-0.dll',
)

LINUX_LIBRARIES = (
    'libffi.so.8',
    'libglib-2.0.so.0',
    'libgobject-2.0.so.0',
    'libgio-2.0.so.0',
    'libfontconfig.so.1',
    'libfreetype.so.6',
    'libharfbuzz.so.0',
    'libcairo.so.2',
    'libpango-1.0.so.0',
    'libpangoft2-1.0.so.0',
    'libpangocairo-1.0.so.0',
)

MACOS_LIBRARIES = (
    'libgobject-2.0.0.dylib',
    'libpango-1.0.0.dylib',
    'libharfbuzz.0.dylib',
    'libfontconfig.1.dylib',
    'libpangoft2-1.0.0.dylib',
)

MACOS_SEED_LIBRARY_PATTERNS = (
    'libpango-1.0*.dylib',
    'libpangoft2-1.0*.dylib',
    'libpangocairo-1.0*.dylib',
    'libcairo*.dylib',
    'libfontconfig*.dylib',
    'libfreetype*.dylib',
    'libharfbuzz*.dylib',
)

MACOS_LIBRARY_ALIASES = {
    'fontconfig': 'libfontconfig.1.dylib',
    'fontconfig-1': 'libfontconfig.1.dylib',
    'gobject-2.0': 'libgobject-2.0.0.dylib',
    'gobject-2.0-0': 'libgobject-2.0.0.dylib',
    'harfbuzz': 'libharfbuzz.0.dylib',
    'harfbuzz-0.0': 'libharfbuzz.0.dylib',
    'libfontconfig-1': 'libfontconfig.1.dylib',
    'libfontconfig-1.dll': 'libfontconfig.1.dylib',
    'libfontconfig.1.dylib': 'libfontconfig.1.dylib',
    'libfontconfig.so.1': 'libfontconfig.1.dylib',
    'libgobject-2.0-0': 'libgobject-2.0.0.dylib',
    'libgobject-2.0-0.dll': 'libgobject-2.0.0.dylib',
    'libgobject-2.0.0.dylib': 'libgobject-2.0.0.dylib',
    'libgobject-2.0.so.0': 'libgobject-2.0.0.dylib',
    'libharfbuzz-0': 'libharfbuzz.0.dylib',
    'libharfbuzz-0.dll': 'libharfbuzz.0.dylib',
    'libharfbuzz.0.dylib': 'libharfbuzz.0.dylib',
    'libharfbuzz.so.0': 'libharfbuzz.0.dylib',
    'libpango-1.0-0': 'libpango-1.0.0.dylib',
    'libpango-1.0-0.dll': 'libpango-1.0.0.dylib',
    'libpango-1.0.dylib': 'libpango-1.0.0.dylib',
    'libpango-1.0.so.0': 'libpango-1.0.0.dylib',
    'libpangoft2-1.0-0': 'libpangoft2-1.0.0.dylib',
    'libpangoft2-1.0-0.dll': 'libpangoft2-1.0.0.dylib',
    'libpangoft2-1.0.dylib': 'libpangoft2-1.0.0.dylib',
    'libpangoft2-1.0.so.0': 'libpangoft2-1.0.0.dylib',
    'pango-1.0': 'libpango-1.0.0.dylib',
    'pango-1.0-0': 'libpango-1.0.0.dylib',
    'pangoft2-1.0': 'libpangoft2-1.0.0.dylib',
    'pangoft2-1.0-0': 'libpangoft2-1.0.0.dylib',
}
