#!/usr/bin/env python3
from __future__ import annotations
import argparse, hashlib, shutil, sys, tomllib, urllib.request
from pathlib import Path
ROOT = Path(__file__).resolve().parents[1]
CFG = ROOT / 'config' / 'libraries.toml'

def digest(path: Path, algo: str) -> str:
    h = hashlib.new(algo)
    with path.open('rb') as f:
        for chunk in iter(lambda: f.read(1024 * 1024), b''):
            h.update(chunk)
    return h.hexdigest()

def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument('--refresh', action='store_true')
    ap.add_argument('--write-lock', action='store_true', help='Write config/source-lock.generated.toml with observed SHA-256 sums')
    args = ap.parse_args()
    cfg = tomllib.loads(CFG.read_text(encoding='utf-8'))
    out = ROOT / cfg['build']['download_dir']
    out.mkdir(parents=True, exist_ok=True)
    locked = []
    for item in cfg['library']:
        dst = out / item['archive']
        if args.refresh and dst.exists(): dst.unlink()
        if not dst.exists():
            print(f"download {item['name']} {item['version']}: {item['url']}", flush=True)
            req = urllib.request.Request(item['url'], headers={'User-Agent':'weasyprintlibs-superbuild/2026.1'})
            with urllib.request.urlopen(req) as src, dst.open('wb') as target:
                shutil.copyfileobj(src, target)
        checksum = item.get('checksum', 'unlocked')
        if checksum != 'unlocked':
            algo, expected = checksum.split(':', 1)
            actual = digest(dst, algo)
            if actual != expected:
                raise SystemExit(f'checksum mismatch for {dst.name}: expected {expected}, got {actual}')
        sha256 = digest(dst, 'sha256')
        print(f"ok {dst.name} sha256={sha256}")
        locked.append((item['name'], item['version'], item['url'], item['archive'], sha256))
    if args.write_lock:
        lock = ROOT / 'config' / 'source-lock.generated.toml'
        with lock.open('w', encoding='utf-8') as f:
            f.write('# Generated by scripts/fetch_sources.py --write-lock\n')
            for name, version, url, archive, sha256 in locked:
                f.write(f'\n[[source]]\nname = "{name}"\nversion = "{version}"\nurl = "{url}"\narchive = "{archive}"\nsha256 = "{sha256}"\n')
        print(f'wrote {lock}')
if __name__ == '__main__': main()
