from __future__ import annotations

import argparse
import hashlib
import io
import os
import shutil
import subprocess
import sys
import tarfile
import tomllib
import urllib.request
from pathlib import Path
from typing import Any

import zstandard

ROOT = Path(__file__).resolve().parents[1]
CONFIG_PATH = ROOT / "config" / "windows-packages.toml"


def load_toml(path: Path) -> dict[str, Any]:
    with path.open("rb") as stream:
        return tomllib.load(stream)


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as stream:
        for chunk in iter(lambda: stream.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def find_pacman(explicit: str | None) -> Path:
    candidates = [
        explicit,
        os.environ.get("MSYS2_PACMAN"),
        shutil.which("pacman"),
        r"C:\msys64\usr\bin\pacman.exe",
    ]
    for candidate in candidates:
        if candidate and Path(candidate).is_file():
            return Path(candidate)
    raise RuntimeError(
        "pacman was not found. Run this command in an MSYS2 shell, set "
        "MSYS2_PACMAN, or pass --pacman C:\\msys64\\usr\\bin\\pacman.exe"
    )


def pkginfo_from_archive(path: Path) -> dict[str, str]:
    with path.open("rb") as compressed:
        with zstandard.ZstdDecompressor().stream_reader(compressed) as reader:
            with tarfile.open(fileobj=reader, mode="r|") as archive:
                for member in archive:
                    if member.name.lstrip("./") != ".PKGINFO":
                        continue
                    extracted = archive.extractfile(member)
                    if extracted is None:
                        break
                    result: dict[str, str] = {}
                    for raw_line in io.TextIOWrapper(extracted, encoding="utf-8"):
                        line = raw_line.strip()
                        if not line or line.startswith("#") or " = " not in line:
                            continue
                        key, value = line.split(" = ", 1)
                        result.setdefault(key, value)
                    return result
    raise RuntimeError(f"Archive does not contain .PKGINFO: {path}")


def toml_string(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def write_lock(config: dict[str, Any], archives: list[Path], lock_path: Path) -> None:
    windows = config["windows"]
    base_url = windows["mirror_base_url"].rstrip("/")
    lines = [
        "# Generated by scripts/fetch_windows_packages.py --update-lock",
        "# Commit this file. Normal release builds use --locked.",
        "",
        "[metadata]",
        f"repository = {toml_string(windows['repository'])}",
        f"architecture = {toml_string(windows['architecture'])}",
        f"prefix = {toml_string(windows['prefix'])}",
        f"mirror_base_url = {toml_string(base_url)}",
        "",
    ]

    packages: list[tuple[str, Path, dict[str, str]]] = []
    for archive in archives:
        info = pkginfo_from_archive(archive)
        packages.append((info.get("pkgname", archive.name), archive, info))

    for _, archive, info in sorted(packages, key=lambda item: item[0]):
        lines.extend(
            [
                "[[package]]",
                f"name = {toml_string(info.get('pkgname', archive.name))}",
                f"version = {toml_string(info.get('pkgver', 'unknown'))}",
                f"filename = {toml_string(archive.name)}",
                f"url = {toml_string(base_url + '/' + archive.name)}",
                f"sha256 = {toml_string(sha256(archive))}",
                "",
            ]
        )

    lock_path.parent.mkdir(parents=True, exist_ok=True)
    lock_path.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {lock_path} with {len(packages)} packages")


def update_lock(config: dict[str, Any], pacman_arg: str | None) -> None:
    windows = config["windows"]
    download_dir = ROOT / windows["download_dir"]
    lock_path = ROOT / windows["lock_file"]
    pacman = find_pacman(pacman_arg)

    shutil.rmtree(download_dir, ignore_errors=True)
    download_dir.mkdir(parents=True, exist_ok=True)

    command = [
        str(pacman),
        "-Syw",
        "--noconfirm",
        "--cachedir",
        str(download_dir),
        *windows["packages"],
    ]
    print("Running:", subprocess.list2cmdline(command))
    subprocess.run(command, check=True)

    archives = sorted(download_dir.glob("*.pkg.tar.zst"))
    if not archives:
        raise RuntimeError(f"pacman downloaded no packages to {download_dir}")
    write_lock(config, archives, lock_path)


def download(url: str, destination: Path) -> None:
    temporary = destination.with_suffix(destination.suffix + ".part")
    temporary.unlink(missing_ok=True)
    print(f"Downloading {url}")
    with urllib.request.urlopen(url) as response, temporary.open("wb") as output:
        shutil.copyfileobj(response, output)
    temporary.replace(destination)


def fetch_locked(config: dict[str, Any]) -> None:
    windows = config["windows"]
    lock_path = ROOT / windows["lock_file"]
    if not lock_path.is_file():
        raise RuntimeError(
            f"Missing {lock_path}. On a Windows/MSYS2 update host run:\n"
            "  uv run python scripts/fetch_windows_packages.py --update-lock"
        )

    lock = load_toml(lock_path)
    packages = lock.get("package", [])
    if not packages:
        raise RuntimeError(f"No packages recorded in {lock_path}")

    download_dir = ROOT / windows["download_dir"]
    download_dir.mkdir(parents=True, exist_ok=True)

    for package in packages:
        destination = download_dir / package["filename"]
        expected = package["sha256"].lower()
        if destination.is_file() and sha256(destination) == expected:
            print(f"Using cached {destination.name}")
            continue
        destination.unlink(missing_ok=True)
        download(package["url"], destination)
        actual = sha256(destination)
        if actual != expected:
            destination.unlink(missing_ok=True)
            raise RuntimeError(
                f"SHA-256 mismatch for {package['filename']}: "
                f"expected {expected}, got {actual}"
            )


def main() -> None:
    parser = argparse.ArgumentParser()
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--update-lock", action="store_true")
    mode.add_argument("--locked", action="store_true")
    parser.add_argument("--pacman")
    args = parser.parse_args()

    config = load_toml(CONFIG_PATH)
    if args.update_lock:
        if sys.platform != "win32" and shutil.which("pacman") is None:
            print("Warning: update-lock is normally run on Windows in an MSYS2 shell")
        update_lock(config, args.pacman)
    else:
        fetch_locked(config)


if __name__ == "__main__":
    main()
