from __future__ import annotations

import argparse
import hashlib
import os
import shutil
import subprocess
import sys
import tarfile
import urllib.request
from pathlib import Path, PurePosixPath
from typing import Any

import zstandard

from windows_config import load_toml, load_windows_profile

ROOT = Path(__file__).resolve().parents[1]


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as stream:
        for chunk in iter(lambda: stream.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def find_pacman(explicit: str | None) -> Path:
    candidates = [
        explicit,
        os.environ.get("MSYS2_PACMAN"),
        shutil.which("pacman"),
        r"C:\msys64\usr\bin\pacman.exe",
    ]
    for candidate in candidates:
        if candidate and Path(candidate).is_file():
            return Path(candidate)
    raise RuntimeError(
        "pacman was not found. Run this command in an MSYS2 shell, set "
        "MSYS2_PACMAN, or pass --pacman C:\\msys64\\usr\\bin\\pacman.exe"
    )


def pkginfo_from_archive(path: Path) -> dict[str, str]:
    with path.open("rb") as compressed:
        decompressor = zstandard.ZstdDecompressor()

        with decompressor.stream_reader(compressed) as reader:
            with tarfile.open(fileobj=reader, mode="r|") as archive:
                for member in archive:
                    if PurePosixPath(member.name).name != ".PKGINFO":
                        continue

                    extracted = archive.extractfile(member)
                    if extracted is None:
                        raise RuntimeError(f"Could not extract .PKGINFO from archive: {path}")

                    content = extracted.read().decode("utf-8", errors="strict")
                    result: dict[str, str] = {}

                    for raw_line in content.splitlines():
                        line = raw_line.strip()
                        if not line or line.startswith("#"):
                            continue

                        key, separator, value = line.partition(" = ")
                        if not separator:
                            continue

                        # .PKGINFO can contain repeated keys such as depend.
                        # pkgname/pkgver only need the first value.
                        result.setdefault(key, value)

                    if not result:
                        raise RuntimeError(f".PKGINFO is empty or invalid in archive: {path}")

                    return result

    raise RuntimeError(f"Archive does not contain .PKGINFO: {path}")


def toml_string(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def write_lock(profile: dict[str, Any], archives: list[Path], lock_path: Path) -> None:
    base_url = profile["mirror_base_url"].rstrip("/")
    lines = [
        "# Generated by scripts/fetch_windows_packages.py --update-lock",
        "# Commit this file. Normal release builds use --locked.",
        "",
        "[metadata]",
        f"profile = {toml_string(profile['profile'])}",
        f"repository = {toml_string(profile['repository'])}",
        f"architecture = {toml_string(profile['architecture'])}",
        f"prefix = {toml_string(profile['prefix'])}",
        f"mirror_base_url = {toml_string(base_url)}",
        "",
    ]

    packages: list[tuple[str, Path, dict[str, str]]] = []
    for archive in archives:
        info = pkginfo_from_archive(archive)
        packages.append((info.get("pkgname", archive.name), archive, info))

    for _, archive, info in sorted(packages, key=lambda item: item[0]):
        lines.extend(
            [
                "[[package]]",
                f"name = {toml_string(info.get('pkgname', archive.name))}",
                f"version = {toml_string(info.get('pkgver', 'unknown'))}",
                f"filename = {toml_string(archive.name)}",
                f"url = {toml_string(base_url + '/' + archive.name)}",
                f"sha256 = {toml_string(sha256(archive))}",
                "",
            ]
        )

    lock_path.parent.mkdir(parents=True, exist_ok=True)
    lock_path.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {lock_path} with {len(packages)} packages for {profile['profile']}")


def update_lock(profile: dict[str, Any], pacman_arg: str | None) -> None:
    download_dir = ROOT / profile["download_dir"]
    lock_path = ROOT / profile["lock_file"]
    pacman = find_pacman(pacman_arg)

    shutil.rmtree(download_dir, ignore_errors=True)
    download_dir.mkdir(parents=True, exist_ok=True)

    command = [
        str(pacman),
        "-Syw",
        "--noconfirm",
        "--cachedir",
        str(download_dir),
        *profile["packages"],
    ]
    print("Running:", subprocess.list2cmdline(command))
    subprocess.run(command, check=True)

    archives = sorted(download_dir.glob("*.pkg.tar.zst"))
    if not archives:
        raise RuntimeError(f"pacman downloaded no packages to {download_dir}")
    write_lock(profile, archives, lock_path)


def download(url: str, destination: Path) -> None:
    temporary = destination.with_suffix(destination.suffix + ".part")
    temporary.unlink(missing_ok=True)
    print(f"Downloading {url}")
    with urllib.request.urlopen(url) as response, temporary.open("wb") as output:
        shutil.copyfileobj(response, output)
    temporary.replace(destination)


def verify_lock_metadata(profile: dict[str, Any], lock: dict[str, Any], lock_path: Path) -> None:
    metadata = lock.get("metadata")
    if not isinstance(metadata, dict):
        raise RuntimeError(f"Missing [metadata] in {lock_path}")

    expected = {
        "repository": profile["repository"],
        "architecture": profile["architecture"],
        "prefix": profile["prefix"],
        "mirror_base_url": profile["mirror_base_url"].rstrip("/"),
    }
    mismatches = [
        f"{key}: {metadata.get(key)!r} != {value!r}"
        for key, value in expected.items()
        if metadata.get(key) != value
    ]
    recorded_profile = metadata.get("profile")
    if recorded_profile is not None and recorded_profile != profile["profile"]:
        mismatches.append(
            f"profile: {recorded_profile!r} != {profile['profile']!r}"
        )
    if mismatches:
        formatted = "\n".join(f"  - {item}" for item in mismatches)
        raise RuntimeError(
            f"Lockfile {lock_path} does not match the selected profile:\n{formatted}"
        )


def fetch_locked(profile: dict[str, Any]) -> None:
    lock_path = ROOT / profile["lock_file"]
    if not lock_path.is_file():
        raise RuntimeError(
            f"Missing {lock_path}. On a matching Windows/MSYS2 host run:\n"
            "  uv run python scripts/fetch_windows_packages.py "
            f"--profile {profile['profile']} --update-lock"
        )

    lock = load_toml(lock_path)
    verify_lock_metadata(profile, lock, lock_path)
    packages = lock.get("package", [])
    if not packages:
        raise RuntimeError(f"No packages recorded in {lock_path}")

    download_dir = ROOT / profile["download_dir"]
    download_dir.mkdir(parents=True, exist_ok=True)

    for package in packages:
        destination = download_dir / package["filename"]
        expected = package["sha256"].lower()
        if destination.is_file() and sha256(destination) == expected:
            print(f"Using cached {destination.name}")
            continue
        destination.unlink(missing_ok=True)
        download(package["url"], destination)
        actual = sha256(destination)
        if actual != expected:
            destination.unlink(missing_ok=True)
            raise RuntimeError(
                f"SHA-256 mismatch for {package['filename']}: expected {expected}, got {actual}"
            )


def main() -> None:
    parser = argparse.ArgumentParser()
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--update-lock", action="store_true")
    mode.add_argument("--locked", action="store_true")
    parser.add_argument("--profile")
    parser.add_argument("--pacman")
    args = parser.parse_args()

    profile = load_windows_profile(args.profile)
    if args.update_lock:
        if sys.platform != "win32" and shutil.which("pacman") is None:
            print("Warning: update-lock is normally run on Windows in an MSYS2 shell")
        update_lock(profile, args.pacman)
    else:
        fetch_locked(profile)


if __name__ == "__main__":
    main()
